### In This Script I will use python to clean data and then i will upload tables into database

In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
from sqlalchemy import create_engine

In [2]:
df1 = pd.read_csv(r'Customers_Info.csv',encoding='latin-1')

In [3]:
df1.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,EstimatedSalary,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,15634602,Hargrave,619,FRA,Female,42.0,2,101348.88,NaN,NaN,NaN,NaN,NaN,NaN
1,15647311,Hill,608,Spain,Female,41.0,1,112542.58,NaN,NaN,NaN,NaN,NaN,NaN
2,15619304,Onio,502,French,Female,42.0,8,113931.57,NaN,NaN,NaN,NaN,NaN,NaN
3,15701354,Boni,699,FRA,Female,39.0,1,93826.63,NaN,NaN,NaN,NaN,NaN,NaN
4,15737888,Mitchell,850,Spain,Female,43.0,2,79084.1,NaN,NaN,NaN,NaN,NaN,NaN

# Cleaning of Customers_Info df1

In [4]:
df1 = df1.iloc[0:,0:8]

In [5]:
df1

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,EstimatedSalary
0,15634602,Hargrave,619,FRA,Female,42.0,2,101348.88
1,15647311,Hill,608,Spain,Female,41.0,1,112542.58
2,15619304,Onio,502,French,Female,42.0,8,113931.57
3,15701354,Boni,699,FRA,Female,39.0,1,93826.63
4,15737888,Mitchell,850,Spain,Female,43.0,2,79084.1
...,...,...,...,...,...,...,...,...
9996,15569892,Johnstone,516,French,Male,35.0,10,101699.77
9997,15584532,Liu,709,FRA,Female,36.0,7,42085.58
9998,15682355,Sabbatini,772,Germany,Male,42.0,3,92888.52
9999,15628319,Walker,792,French,Female,28.0,4,38190.78
10000,15628319,Walker,792,French,Female,28.0,4,38190.78

In [6]:
df1.isna().sum()

CustomerId         0
Surname            3
CreditScore        0
Geography          0
Gender             0
Age                3
Tenure             0
EstimatedSalary    0
dtype: int64

In [7]:
df1['Age'].fillna(df1['Age'].median(),inplace=True)

C:\Users\Amish Ilyas\AppData\Local\Temp\ipykernel_14992\2947180757.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Age'].fillna(df1['Age'].median(),inplace=True)

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10001 entries, 0 to 10000
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10001 non-null  int64
 1   Surname          9998 non-null   object
 2   CreditScore      10001 non-null  int64
 3   Geography        10001 non-null  object
 4   Gender           10001 non-null  object
 5   Age              10001 non-null  float64
 6   Tenure           10001 non-null  int64
 7   EstimatedSalary  10001 non-null  object
dtypes: float64(1), int64(3), object(4)
memory usage: 625.2+ KB

In [9]:
df1['Geography'].unique()

array(['FRA', 'Spain', 'French', 'France', 'Germany'], dtype=object)

In [10]:
df1['Geography'] = df1['Geography'].replace('FRA','France')

In [11]:
df1['Geography'] = df1['Geography'].replace('French','France')

In [12]:
df1['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [13]:
df1['Age'] = df1['Age'].astype(int)

In [14]:
df1['EstimatedSalary'] = df1['EstimatedSalary'].str.strip('\x80')

In [15]:
df1['EstimatedSalary'] = pd.to_numeric(df1['EstimatedSalary'],errors='coerce')

In [16]:
df1.rename(columns={'Geography':'Country'},inplace=True)

In [17]:
for i in df1.columns:
    print(df1[i].name)
    print(df1[i].unique())

CustomerId
[15634602 15647311 15619304 ... 15584532 15682355 15628319]
Surname
['Hargrave' 'Hill' 'Onio' ... 'Kashiwagi' 'Aldridge' 'Burbidge']
CreditScore
[619 608 502 699 850 645 822 376 501 684 528 497 476 549 635 616 653 587
 726 732 636 510 669 846 577 756 571 574 411 591 533 553 520 722 475 490
 804 582 472 465 556 834 660 776 829 637 550 698 585 788 655 601 656 725
 511 614 742 687 555 603 751 581 735 661 675 738 813 657 604 519 664 678
 757 416 665 777 543 506 493 652 750 729 646 647 808 524 769 730 515 773
 814 710 413 623 670 622 785 605 479 685 538 562 721 628 668 828 674 625
 432 770 758 795 686 789 589 461 584 579 663 682 793 691 485 650 754 535
 716 539 706 586 631 717 800 683 704 615 667 484 480 578 512 606 597 778
 514 525 715 580 807 521 759 516 711 618 643 671 689 620 676 572 695 592
 567 694 547 594 673 610 767 763 712 703 662 659 523 772 545 634 739 771
 681 544 696 766 727 693 557 531 498 651 791 733 811 707 714 782 775 799
 602 744 588 747 583 627 731 629 438 642 806 474 559 429 680 749 734 644
 626 649 805 718 840 630 654 762 568 613 522 737 648 443 640 540 460 593
 801 611 802 745 483 690 492 709 705 560 752 701 537 487 596 702 486 724
 548 464 790 534 748 494 590 468 509 818 816 536 753 774 621 569 658 798
 641 542 692 639 765 570 638 599 632 779 527 564 833 504 842 508 417 598
 741 607 761 848 546 439 755 760 526 713 700 666 566 495 688 612 477 427
 839 819 720 459 503 624 529 563 482 796 445 746 786 554 672 787 499 844
 450 815 838 803 736 633 600 679 517 792 743 488 421 841 708 507 505 456
 435 561 518 565 728 784 552 609 764 697 723 551 444 719 496 541 830 812
 677 420 595 617 809 500 826 434 513 478 797 363 399 463 780 452 575 837
 794 824 428 823 781 849 489 431 457 768 831 359 820 573 576 558 817 449
 440 415 821 530 350 446 425 740 481 783 358 845 451 458 469 423 404 836
 473 835 466 491 351 827 843 365 532 414 453 471 401 810 832 470 447 422
 825 430 436 426 408 847 418 437 410 454 407 455 462 386 405 383 395 467
 433 442 424 448 441 367 412 382 373 419]
Country
['France' 'Spain' 'Germany']
Gender
['Female' 'Male']
Age
[42 41 39 43 44 50 29 27 31 24 34 25 35 45 58 32 38 46 36 37 33 40 51 61
 49 19 66 56 26 21 55 75 22 30 28 65 48 52 57 73 47 54 72 20 67 79 62 53
 80 59 68 23 60 70 63 64 18 82 69 74 71 76 77 88 85 84 78 81 92 83]
Tenure
[ 2  1  8  7  4  6  3 10  5  9  0]
EstimatedSalary
[101348.88 112542.58 113931.57 ...  42085.58  92888.52  38190.78]

# Cleaning of Account_Info df2

In [18]:
df2 = pd.read_csv(r'Account_info.csv',encoding='latin-1')

In [19]:
df2.head()

,CustomerId,Balance,NumOfProducts,HasCrCard,Tenure,IsActiveMember,Exited,Unnamed: 7,Unnamed: 8
0,15634602,0.0,1,Yes,2,Yes,1,NaN,NaN
1,15634602,0.0,1,Yes,2,Yes,1,NaN,NaN
2,15647311,83807.86,1,Yes,1,Yes,0,NaN,NaN
3,15619304,159660.8,3,No,8,No,1,NaN,NaN
4,15701354,0.0,2,No,1,No,0,NaN,NaN

In [20]:
df2 = df2.iloc[0:,0:7]

In [21]:
for i in df2.columns:
    print(df2[i].name)
    print(df2[i].unique())

CustomerId
[15634602 15647311 15619304 ... 15584532 15682355 15628319]
Balance
['\x800.0' '\x8083807.86' '\x80159660.8' ... '\x8057369.61' '\x8075075.31'
 '\x80130142.79']
NumOfProducts
[1 3 2 4]
HasCrCard
['Yes' 'No']
Tenure
[ 2  1  8  7  4  6  3 10  5  9  0]
IsActiveMember
['Yes' 'No']
Exited
[1 0]

In [22]:
df2['Balance'] = df2['Balance'].str.strip('\x80')

In [23]:
df2['Balance'] = pd.to_numeric(df2['Balance'],errors='coerce')

In [24]:
for i in df2.columns:
    print(df2[i].name)
    print(df2[i].unique())

CustomerId
[15634602 15647311 15619304 ... 15584532 15682355 15628319]
Balance
[     0.    83807.86 159660.8  ...  57369.61  75075.31 130142.79]
NumOfProducts
[1 3 2 4]
HasCrCard
['Yes' 'No']
Tenure
[ 2  1  8  7  4  6  3 10  5  9  0]
IsActiveMember
['Yes' 'No']
Exited
[1 0]

In [25]:
df2.rename(columns={'HasCrCard' : 'Has_Credit_Card'},inplace=True)

# Data is Cleaned

In [26]:
df1.head() ## Customers_Info Table

,CustomerId,Surname,CreditScore,Country,Gender,Age,Tenure,EstimatedSalary
0,15634602,Hargrave,619,France,Female,42,2,101348.88
1,15647311,Hill,608,Spain,Female,41,1,112542.58
2,15619304,Onio,502,France,Female,42,8,113931.57
3,15701354,Boni,699,France,Female,39,1,93826.63
4,15737888,Mitchell,850,Spain,Female,43,2,79084.10

In [27]:
df2.head() ### Account_Info Table

,CustomerId,Balance,NumOfProducts,Has_Credit_Card,Tenure,IsActiveMember,Exited
0,15634602,0.00,1,Yes,2,Yes,1
1,15634602,0.00,1,Yes,2,Yes,1
2,15647311,83807.86,1,Yes,1,Yes,0
3,15619304,159660.80,3,No,8,No,1
4,15701354,0.00,2,No,1,No,0

In [28]:
df1.drop_duplicates(inplace=True)
df2.drop_duplicates(inplace=True)

In [29]:
def Age_Grouping(x):
    if 18 <= x <= 25:
        return '18-25'
    elif 26 <= x <= 35:
        return '26-35'
    elif 36 <= x <= 45:
        return '36-45'
    elif 46 <= x <= 55:
        return '46-55' 
    elif 56 <= x <= 65:
        return '56-65'
    elif 66 <= x <= 75:
        return '66-75'
    elif 76 <= x <= 85:
        return '76-85'
    else:
        return '86+'

In [30]:
df1['Age_Groups'] = df1['Age'].apply(Age_Grouping)

In [31]:
df1.head()

,CustomerId,Surname,CreditScore,Country,Gender,Age,Tenure,EstimatedSalary,Age_Groups
0,15634602,Hargrave,619,France,Female,42,2,101348.88,36-45
1,15647311,Hill,608,Spain,Female,41,1,112542.58,36-45
2,15619304,Onio,502,France,Female,42,8,113931.57,36-45
3,15701354,Boni,699,France,Female,39,1,93826.63,36-45
4,15737888,Mitchell,850,Spain,Female,43,2,79084.10,36-45

In [32]:
df1['Age_Groups'].unique()

array(['36-45', '46-55', '26-35', '18-25', '56-65', '66-75', '76-85',
       '86+'], dtype=object)

In [33]:
df2.drop(columns={'Tenure'},inplace=True)

In [34]:
df1.head()

,CustomerId,Surname,CreditScore,Country,Gender,Age,Tenure,EstimatedSalary,Age_Groups
0,15634602,Hargrave,619,France,Female,42,2,101348.88,36-45
1,15647311,Hill,608,Spain,Female,41,1,112542.58,36-45
2,15619304,Onio,502,France,Female,42,8,113931.57,36-45
3,15701354,Boni,699,France,Female,39,1,93826.63,36-45
4,15737888,Mitchell,850,Spain,Female,43,2,79084.10,36-45

In [35]:
df2.head()

   CustomerId    Balance  NumOfProducts Has_Credit_Card IsActiveMember  Exited
0    15634602       0.00              1             Yes            Yes       1
2    15647311   83807.86              1             Yes            Yes       0
3    15619304  159660.80              3              No             No       1
4    15701354       0.00              2              No             No       0
5    15737888  125510.82              1             Yes            Yes       0

In [36]:
df1.drop(columns={'Surname'},inplace=True)

In [37]:
df1.head()

,CustomerId,CreditScore,Country,Gender,Age,Tenure,EstimatedSalary,Age_Groups
0,15634602,619,France,Female,42,2,101348.88,36-45
1,15647311,608,Spain,Female,41,1,112542.58,36-45
2,15619304,502,France,Female,42,8,113931.57,36-45
3,15701354,699,France,Female,39,1,93826.63,36-45
4,15737888,850,Spain,Female,43,2,79084.10,36-45

In [38]:
df1['CreditScore'].unique()

array([619, 608, 502, 699, 850, 645, 822, 376, 501, 684, 528, 497, 476,
       549, 635, 616, 653, 587, 726, 732, 636, 510, 669, 846, 577, 756,
       571, 574, 411, 591, 533, 553, 520, 722, 475, 490, 804, 582, 472,
       465, 556, 834, 660, 776, 829, 637, 550, 698, 585, 788, 655, 601,
       656, 725, 511, 614, 742, 687, 555, 603, 751, 581, 735, 661, 675,
       738, 813, 657, 604, 519, 664, 678, 757, 416, 665, 777, 543, 506,
       493, 652, 750, 729, 646, 647, 808, 524, 769, 730, 515, 773, 814,
       710, 413, 623, 670, 622, 785, 605, 479, 685, 538, 562, 721, 628,
       668, 828, 674, 625, 432, 770, 758, 795, 686, 789, 589, 461, 584,
       579, 663, 682, 793, 691, 485, 650, 754, 535, 716, 539, 706, 586,
       631, 717, 800, 683, 704, 615, 667, 484, 480, 578, 512, 606, 597,
       778, 514, 525, 715, 580, 807, 521, 759, 516, 711, 618, 643, 671,
       689, 620, 676, 572, 695, 592, 567, 694, 547, 594, 673, 610, 767,
       763, 712, 703, 662, 659, 523, 772, 545, 634, 739, 771, 681, 544,
       696, 766, 727, 693, 557, 531, 498, 651, 791, 733, 811, 707, 714,
       782, 775, 799, 602, 744, 588, 747, 583, 627, 731, 629, 438, 642,
       806, 474, 559, 429, 680, 749, 734, 644, 626, 649, 805, 718, 840,
       630, 654, 762, 568, 613, 522, 737, 648, 443, 640, 540, 460, 593,
       801, 611, 802, 745, 483, 690, 492, 709, 705, 560, 752, 701, 537,
       487, 596, 702, 486, 724, 548, 464, 790, 534, 748, 494, 590, 468,
       509, 818, 816, 536, 753, 774, 621, 569, 658, 798, 641, 542, 692,
       639, 765, 570, 638, 599, 632, 779, 527, 564, 833, 504, 842, 508,
       417, 598, 741, 607, 761, 848, 546, 439, 755, 760, 526, 713, 700,
       666, 566, 495, 688, 612, 477, 427, 839, 819, 720, 459, 503, 624,
       529, 563, 482, 796, 445, 746, 786, 554, 672, 787, 499, 844, 450,
       815, 838, 803, 736, 633, 600, 679, 517, 792, 743, 488, 421, 841,
       708, 507, 505, 456, 435, 561, 518, 565, 728, 784, 552, 609, 764,
       697, 723, 551, 444, 719, 496, 541, 830, 812, 677, 420, 595, 617,
       809, 500, 826, 434, 513, 478, 797, 363, 399, 463, 780, 452, 575,
       837, 794, 824, 428, 823, 781, 849, 489, 431, 457, 768, 831, 359,
       820, 573, 576, 558, 817, 449, 440, 415, 821, 530, 350, 446, 425,
       740, 481, 783, 358, 845, 451, 458, 469, 423, 404, 836, 473, 835,
       466, 491, 351, 827, 843, 365, 532, 414, 453, 471, 401, 810, 832,
       470, 447, 422, 825, 430, 436, 426, 408, 847, 418, 437, 410, 454,
       407, 455, 462, 386, 405, 383, 395, 467, 433, 442, 424, 448, 441,
       367, 412, 382, 373, 419])

In [39]:
def CreditScore_Status(score):
        if score < 580:
            return "Poor"
        elif 580 <= score < 670:
            return "Fair"
        elif 670 <= score < 740:
            return "Good"
        else:
            return "Excellent"

In [40]:
df1['Credit_Score_Status'] = df1['CreditScore'].apply(CreditScore_Status)

In [41]:
def categorize_balance(balance):
    if balance == 0:
        return "0"
    elif balance <= 50000:
        return "1-50000"
    elif balance <= 150000:
        return "50001-150000"
    else:
        return "150001+"

In [43]:
df2['Balance_Category'] = df2['Balance'].apply(categorize_balance)

In [45]:
df2.head()

,CustomerId,Balance,NumOfProducts,Has_Credit_Card,IsActiveMember,Exited,Balance_Category
0,15634602,0.00,1,Yes,Yes,1,0
2,15647311,83807.86,1,Yes,Yes,0,50001-150000
3,15619304,159660.80,3,No,No,1,150001+
4,15701354,0.00,2,No,No,0,0
5,15737888,125510.82,1,Yes,Yes,0,50001-150000

# Now It's Time to Import Data into Database

In [46]:
db_config = {
    'database':'bank_churn_db',
    'Hostname':'127.0.0.1',
    'Port':3306,
    'Username':'root',
    'Password':'7867'
}

In [47]:
connection_string = f"mysql+pymysql://{db_config['Username']}:{db_config['Password']}@{db_config['Hostname']}:{db_config['Port']}/{db_config['database']}"

In [48]:
db = create_engine(connection_string)

In [49]:
con = db.connect()

In [50]:
df1.to_sql(name='Customers_Info',con=con,if_exists='replace',index=False)

C:\Users\Amish Ilyas\AppData\Local\Temp\ipykernel_14992\2422495705.py:1: UserWarning: The provided table name 'Customers_Info' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df1.to_sql(name='Customers_Info',con=con,if_exists='replace',index=False)

10000

In [51]:
df2.to_sql(name='Account_Info',con=con,if_exists='replace',index=False)

C:\Users\Amish Ilyas\AppData\Local\Temp\ipykernel_14992\806364858.py:1: UserWarning: The provided table name 'Account_Info' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df2.to_sql(name='Account_Info',con=con,if_exists='replace',index=False)

10000

# Work Done