In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r'E:\Data Analyst Roadmap\Google Data Analytics Certificate Course\Python\Alex the Analyst Playlist of Python\Pandas\Movie-Data.xlsx')

In [4]:
df

,Movie Title,Release Date,Wikipedia URL,Genre,Director (1),Director (2),Cast (1),Cast (2),Cast (3),Cast (4),Cast (5),Budget,Revenue
0,10 Cloverfield Lane,2016-03-08,https://en.wikipedia.org/wiki/10_Cloverfield_Lane,Thriller,Dan Trachtenberg,NaN,Mary Elizabeth Winstead,John Goodman,John Gallagher,NaN,NaN,15000000,108300000
1,13 Hours: The Secret Soldiers of Benghazi,2016-01-15,https://en.wikipedia.org/wiki/13_Hours:_The_Se...,Action,Michael Bay,NaN,James Badge Dale,John Krasinski,Toby Stephens,Pablo Schreiber,Max Martini,45000000,69400000
2,2 Guns,2013-08-02,https://en.wikipedia.org/wiki/2_Guns,Action,Baltasar Kormákur,NaN,Mark Wahlberg,Denzel Washington,Paula Patton,Bill Paxton,Edward James Olmos,61000000,131900000
3,21 Jump Street,2012-03-16,https://en.wikipedia.org/wiki/21_Jump_Street_(...,Comedy,Phil Lord,Chris Miller,Jonah Hill,Channing Tatum,Ice Cube,Brie Larson,Rob Riggle,55000000,201500000
4,22 Jump Street,2014-06-04,https://en.wikipedia.org/wiki/22_Jump_Street,Action,Phil Lord,Chris Miller,Channing Tatum,Jonah Hill,Ice Cube,NaN,NaN,84500000,331300000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,X-Men: Days of Future Past,2014-05-10,https://en.wikipedia.org/wiki/X-Men:_Days_of_F...,Action,Bryan Singer,NaN,Hugh Jackman,James McAvoy,Michael Fassbender,Halle Berry,Jennifer Lawrence,200000000,747900000
504,You're Next,2013-08-23,https://en.wikipedia.org/wiki/You%2527re_Next,Horror,Adam Wingard,NaN,Sharni Vinson,Joe Swanberg,AJ Bowen,Nicholas Tucci,Barbara Crampton,1000000,26800000
505,Zero Dark Thirty,2012-12-19,https://en.wikipedia.org/wiki/Zero_Dark_Thirty,Drama,Kathryn Bigelow,NaN,Jessica Chastain,Chris Pratt,Joel Edgerton,Kyle Chandler,Jason Clarke,40000000,132800000
506,Zhong Kui: Snow Girl and the Dark Crystal,2015-02-19,https://en.wikipedia.org/wiki/Zhong_Kui:_Snow_...,Romance,Peter Pau,NaN,Li Bingbing,Chen Kun,Yang Zishan,Winston Chao,Bao Bei'er,30000000,64470000
507,Zoolander 2,2016-02-12,https://en.wikipedia.org/wiki/Zoolander_2,Comedy,Ben Stiller,NaN,Ben Stiller,Owen Wilson,Christine Taylor,Will Ferrell,Penélope Cruz,50000000,56000000

In [5]:
by_Movies = df.set_index('Movie Title')

In [9]:
Most_Revenue_Movies = by_Movies.filter(items=['Budget','Revenue'],axis=1).sort_values(by='Revenue',ascending=False)

In [10]:
Most_Revenue_Movies

                                                Budget    Revenue
Movie Title
Despicable Me 2                               76000000  970800000
The Hobbit: The Battle of the Five Armies    250000000  956000000
Ice Age: Continental Drift                    95000000  877000000
Batman v Superman: Dawn of Justice           250000000  872700000
The Twilight Saga: Breaking Dawn – Part 2    120000000  829700000
...                                                ...        ...
The Letters                                    1000000    1600000
Lazer Team                                     2400000    1600000
The Oogieloves in the Big Balloon Adventure   20000000    1100000
Ain't Them Bodies Saints                       4000000    1000000
No One Lives                                   2900000    1000000

[508 rows x 2 columns]

In [16]:
Top_20_Movies_By_Revenue = Most_Revenue_Movies.head(20)

In [17]:
Top_20_Movies_By_Revenue

                                              Budget    Revenue
Movie Title
Despicable Me 2                             76000000  970800000
The Hobbit: The Battle of the Five Armies  250000000  956000000
Ice Age: Continental Drift                  95000000  877000000
Batman v Superman: Dawn of Justice         250000000  872700000
The Twilight Saga: Breaking Dawn – Part 2  120000000  829700000
Fast & Furious 6                           160000000  788700000
Deadpool                                    58000000  782600000
The Amazing Spider-Man                     230000000  757900000
The Hunger Games: Mockingjay – Part 1      125000000  755400000
X-Men: Days of Future Past                 200000000  747900000
Madagascar 3: Europe's Most Wanted         145000000  746900000
The Secret Life of Pets                     75000000  724900000
Captain America: The Winter Soldier        170000000  714400000
Dawn of the Planet of the Apes             235000000  710600000
The Hunger Games                            78000000  694400000
Mission: Impossible – Rogue Nation         150000000  682300000
Interstellar                               165000000  675100000
Man of Steel                               225000000  668000000
The Hunger Games: Mockingjay – Part 2      160000000  653400000
Suicide Squad                              175000000  636700000

In [18]:
Top_20_Movies_By_Revenue.filter(like='Amazing',axis= 0)

                           Budget    Revenue
Movie Title
The Amazing Spider-Man  230000000  757900000